# Generated by Django 3.2.5 on 2021-07-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210706_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpg', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
